name: PR Checklist
description: Required checklist

body:
  - type: markdown
    attributes:
      value: |
        ## Notes for reviewers
        None.

  - type: dropdown
    attributes:
      label: Included in PHPStan?
      options:
        - Yes
        - No
        - N/A
    validations:
      required: true
